parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(SQLSRV_DATABASE_URL)%'
                driver: 'sqlsrv'
                #server_version: '5.7'
                charset: utf-8
#                default_table_options:
#                    charset: utf-8
#                    collate: utf8mb4_unicode_ci
#                mapping_types:
#                    idstr: string
#                    useridstr: string
#                    namepartstr: string
#                    sexstr: string
                schema_filter: /Case/
                #schema_filter: /Cases/
#    orm:
#        auto_generate_proxy_classes: true
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        mappings:
#            App:
#                is_bundle: false
#                type: annotation
#                dir: '%kernel.project_dir%/src/Entity'
#                prefix: 'App\Entity'
#                alias: App

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/'
                        prefix: 'App\Entity\'
                        alias: App